### ISSUE TITLE
New string interpolation breaks current version

### ISSUE THREAD

**Issue by normanjaeckel** [lukewilliamboswell/roc-parser#7]
Using the new nightly which implements the new string interpolation syntax (using `$` instead of `\`) breaks the current release:

https://github.com/lukewilliamboswell/roc-parser/blob/main/package/String.roc#L166

I got

```
── ENDLESS STRING ─ .../-e3ebWWmlFPfe9fYrr2z1urfslzygbtQQsl69iH1qzQ/String.roc ─

I cannot find the end of this string:

166│  expect parseStr anyCodeunit "$" == Ok '$'
```

after updating to the new nightly build.

**Comment by lukewilliamboswell** [comment]
Thank you for reporting this 👍
